# Generated by Django 2.2.3 on 2020-04-17 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_entities', '0006_auto_20200417_1746'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pokemon',
            name='title',
        ),
        migrations.AddField(
            model_name='pokemon',
            name='title_ru',
            field=models.TextField(default='завр', verbose_name='Название покемона на русском'),
        ),
    ]
