# Generated by Django 2.2.3 on 2020-04-17 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_entities', '0012_auto_20200417_2225'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokemonelementtype',
            name='strong_against',
            field=models.ManyToManyField(blank=True, related_name='_pokemonelementtype_strong_against_+', to='pokemon_entities.PokemonElementType'),
        ),
    ]
